spring:
  application:
    name: cdp-segment-service
server:
  port: 19160
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yaml
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cdp_demo?useSSL=false&serverTimezone=UTC
    username: root
    password: root
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  kafka:
    bootstrap-servers: 127.0.0.1:9092
